### ISSUE TITLE
[PATCH] -g c'est bien

### ISSUE THREAD

**Issue by gabc** [316k/stackulator-ii#1]
From 5facfddbceab0f56800463578c5d1c596bf22fd3 Mon Sep 17 00:00:00 2001
From: Gabriel Beauchamp beauchampgabriel@gmail.com
Date: Wed, 7 Oct 2015 17:25:18 -0400
## Subject: [PATCH] -g c'est bien

 Makefile | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
diff --git a/Makefile b/Makefile
index f87bcf2..d9047f9 100644
--- a/Makefile
+++ b/Makefile
@@ -1,5 +1,5 @@
 CC=gcc
-CFLAGS=-Wall
+CFLAGS=-Wall -g

 build: *.c
##         clear

1.9.1

**Comment by 316k** [comment]
Thanks !
